"""
scripts/colab_setup.py
=======================
Run this on Google Colab to start the chatbot backend with a public URL.

Usage in Colab:
    # 1. Upload the project zip and extract:
    !unzip llama-chatbot.zip -d /content/
    %cd /content/llama-chatbot

    # 2. Install dependencies:
    !pip install -q -r requirements.txt

    # 3. Run this setup script:
    exec(open('scripts/colab_setup.py').read())

    # OR in one cell:
    %run scripts/colab_setup.py
"""

import os
import sys
import subprocess
import threading
import time

print("=" * 60)
print("  LLaMA 3 Chatbot — Google Colab Setup")
print("=" * 60)

# ── Step 1: Make sure we're in the right directory ────────────────────────
script_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(script_dir)
os.chdir(project_root)
sys.path.insert(0, project_root)
print(f"[1/5] Working directory: {project_root}")

# ── Step 2: Collect API keys interactively ────────────────────────────────
print("\n[2/5] Configure API keys")
print("      (Get Groq key FREE at https://console.groq.com)")

groq_key = os.environ.get('GROQ_API_KEY', '')
if not groq_key:
    groq_key = input("Enter your GROQ_API_KEY (gsk_...): ").strip()

google_client_id = os.environ.get('GOOGLE_CLIENT_ID', '')
google_client_secret = os.environ.get('GOOGLE_CLIENT_SECRET', '')

if not google_client_id:
    print("\n  Google OAuth is optional for Colab testing.")
    print("  To skip, just press Enter for both fields.")
    google_client_id = input("Google Client ID (or Enter to skip): ").strip()
    if google_client_id:
        google_client_secret = input("Google Client Secret: ").strip()

# ── Step 3: Start ngrok tunnel ────────────────────────────────────────────
print("\n[3/5] Starting ngrok tunnel...")
try:
    from pyngrok import ngrok, conf

    # Use authtoken if available (more stable connections)
    ngrok_token = os.environ.get('NGROK_AUTHTOKEN', '')
    if ngrok_token:
        ngrok.set_auth_token(ngrok_token)

    tunnel = ngrok.connect(5000, "http")
    public_url = tunnel.public_url
    print(f"      ✅ Public URL: {public_url}")
    print(f"      🔗 Open this in your browser: {public_url}")

except ImportError:
    print("      Installing pyngrok...")
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "pyngrok"])
    from pyngrok import ngrok
    tunnel = ngrok.connect(5000, "http")
    public_url = tunnel.public_url
    print(f"      ✅ Public URL: {public_url}")

# ── Step 4: Write .env file ───────────────────────────────────────────────
print("\n[4/5] Writing .env configuration...")

redirect_uri = f"{public_url}/auth/callback"

env_content = f"""# Auto-generated by colab_setup.py
GROQ_API_KEY={groq_key}
GROQ_MODEL=llama3-8b-8192
GOOGLE_CLIENT_ID={google_client_id}
GOOGLE_CLIENT_SECRET={google_client_secret}
GOOGLE_REDIRECT_URI={redirect_uri}
FLASK_SECRET_KEY={os.urandom(16).hex()}
FLASK_ENV=development
APP_PORT=5000
DATABASE_PATH=../chatbot.db
"""

with open(os.path.join(project_root, '.env'), 'w') as f:
    f.write(env_content)

print("      ✅ .env file written")

if google_client_id:
    print(f"\n  ⚠️  IMPORTANT: Add this redirect URI to your Google Console:")
    print(f"     {redirect_uri}")
    print("     Go to: console.cloud.google.com → Credentials → Edit your OAuth client")
    input("\n  Press Enter once you've updated the redirect URI in Google Console...")

# ── Step 5: Start Flask server ────────────────────────────────────────────
print("\n[5/5] Starting Flask server...")

def run_server():
    from dotenv import load_dotenv
    load_dotenv(os.path.join(project_root, '.env'))
    os.chdir(os.path.join(project_root, 'backend'))
    sys.path.insert(0, project_root)
    from backend.app import create_app
    app = create_app()
    app.run(host='0.0.0.0', port=5000, debug=False, use_reloader=False)

server_thread = threading.Thread(target=run_server, daemon=True)
server_thread.start()
time.sleep(3)  # Wait for server to start

print("\n" + "=" * 60)
print("  ✅ CHATBOT IS RUNNING!")
print(f"  🌐 URL: {public_url}")
print("=" * 60)
print("\n  Keep this cell running. The server stops if you close it.")
print("  Use Ctrl+C to stop.")

# Keep alive
try:
    while True:
        time.sleep(60)
        print(f"  [still running] URL: {public_url}")
except KeyboardInterrupt:
    print("\n  Server stopped.")
    ngrok.disconnect(public_url)
